cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<book_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<book_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

librarian/urls.py
from django.conf.urls import url
from . import views

app_name = 'librarian'

urlpatterns = [
    url(r'^$', views.book_list, name='book_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.book_list, name='book_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.book_detail, name='book_detail'),
]

mylibrarian/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, name='logout'),
        url(r'^admin/', admin.site.urls),
        url(r'^', include('librarian.urls', namespace='librarian')),
        url(r'^', include('cart.urls', namespace='cart')),
        url('accounts/', include('django.contrib.auth.urls')),
]



def get_absolute_url(self):
    return reverse('librarian:book_detail',
                   args=[self.id, self.slug])

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                                document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

librarian/models.py
from django.db import models
from django.urls import reverse
import re

from django.db.models import Q

class Actor(models.Model):
    name = models.CharField(max_length=32)
    surname = models.CharField(max_length=32)
    age = models.IntegerField()

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
            return self.name

    def get_absolute_url(self):
        return reverse('librarian:book_list_by_category', args=[self.slug])

class Book(models.Model):
    category = models.ForeignKey(Category, related_name='books', on_delete=models.CASCADE)
    book_title = models.CharField(max_length=100, db_index=True)
    field_of_study = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    author = models.CharField(max_length=100, db_index=True)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    shelf_no = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='books/%Y/%m/%d', blank=True)


    class Meta:
        ordering = ('book_title', )
        index_together = (('id', 'slug'),)



    def __str__(self):
            return self.book_title

    def get_absolute_url(self):
        return reverse('librarian:book_detail', args=[self.id, self.slug])

def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:

        >>> normalize_query('  some random  words "chemical reactions  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']

    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]

def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.

    '''
    query = None # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query

cart/forms.py
from django import forms

BOOK_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddBookForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=BOOK_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from librarian.models import Book
from .cart import Cart
from .forms import CartAddBookForm


@require_POST
def cart_add(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    form = CartAddBookForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(book=book, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, book_id):
    cart = Cart(request)
    book = get_object_or_404(Book, id=book_id)
    cart.remove(book)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddBookForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

librarian/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Book
from cart.forms import CartAddBookForm
from .models import Actor
from django import forms


def book_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    books = Book.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        books = Book.objects.filter(category=category)

    context = {
        'category': category,
        'categories': categories,
        'books': books
    }
    return render(request, 'librarian/book/list.html', context)


def book_detail(request, id, slug):
    book = get_object_or_404(Book, id=id, slug=slug, available=True)
    cart_book_form = CartAddBookForm()
    context = {
        'book': book,
        'cart_book_form': cart_book_form
    }
    return render(request, 'librarian/book/detail.html', context)

class ActorSearchForm(forms.Form):
    search_text =  forms.CharField(
        required = False,
        label='Search name or surname!',
        widget=forms.TextInput(attrs={'placeholder': 'search here!'})
    )

    search_age_exact = forms.IntegerField(
        required = False,
        label='Search age (exact match)!'
    )

    search_age_min = forms.IntegerField(
        required = False,
        label='Min age'
    )

    search_age_max = forms.IntegerField(
      required = False,
      label='Max age'
    )

cart/templates/cart/detail.html
{% extends 'librarian/base.html' %}
{% load static %}
{% block title %}
    Your Booking Cart
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
        <h2>Booking Cart: Book a book from the library.
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}R
                        My Booking Order:
                        <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">

                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h2>
            <table class="table table-striped table-hover">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Book</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with book=item.book  %}
                        <tr>
                            <td>
                                <a href="{{ book.get__absolute_url }}">
                                    <img src="{% if book.image %} {{ book.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ book.book_title }}</td>
                            <td>
                                <a href="{% url 'cart:cart_remove' book.id %}">Remove</a>
                            </td>
                        </tr>
                    {% endwith %}
                {% endfor %}

                </tbody>
            </table>
        <p class="text-right">
            <a href= "{% url 'librarian:book_list' %}" class="btn btn-default">Continue Booking</a>
            <a href="" class="btn btn-primary">Checkout</a>
        </p>
        </div>
    </div>
{% endblock %}

librarian/templates/Home.html
{% extends 'librarian/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

librarian/templates/librarian/Home.html
{% extends 'librarian/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

librarian/templates/librarian/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}On-line Library{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">


</head>
<body>
<div>

{% include 'librarian/navbar.html' %}

<div style: align="center" margin-top = "20px" style="margin-top: 4%" > {% include 'librarian/search.html' %}</div>
    <div style: align="center" margin-top="20px" margin-top = "20px" style="margin-top: 4%" > BOOKS RECOMMENDED FOR YOU </div>
{% block content %}


 
{% endblock %}
 <div style: align="right" margin-top = "20px" style="margin-top: 4%" > {% include 'librarian/footer.html' %}
</div>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4/css/bootstrap.min.css">


</body>

</html>

librarian/templates/librarian/book/Home.html
{% extends 'librarian\base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Welcome {{ user.username }}!
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'librarian/login.html' %}">login</a>
{% endif %}
{% endblock %}

librarian/templates/librarian/book/detail.html
{% extends 'librarian/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Books {% endif %}
{% endblock %}
 
{% block content %}
   <div class="container" style="padding-left: 50px>
      <div class="row" align="center" style="margin-top: 6%" >
 
        <div class="col-sm-8 blog-main">
 
          <div class="blog-post">
              <div class="row">
                <div  class="card">
                        <div class="col-md-6 text-right">
                            <img src="{% if book.image %} {{ book.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 100px; width: auto">
                        </div>
                        <div class="col-md-6" style="padding-left: 50px">
                           Title:{{ book.book_title }}
                            <h6> <a href="{{ book.category.get_absolute_url }}">Category:{{ book.category }}</a></h6>
                            <p class="text-muted"> Author:{{ book.author }}</p>

                            <p>Description:{{ book.description|safe|linebreaksbr }}</p>
                             <p>Books available:{{ book.stock|safe|linebreaksbr }}</p>

                            <form action="{% url 'cart:cart_add' book.id %}" method="post">
                                {% csrf_token %}
                                {{ cart_book_form }}
                                <input type="submit" value="add to booking cart" class="btn btn-primary">
                            </form>
                        </div>
                    </div>
                </div>
              </div>
 
 
          </div>
 
        </div>
      </div>
 
    </div>
{% endblock %}

librarian/templates/librarian/book/list.html
{% extends 'librarian/base.html' %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }} {% else %} Books {% endif %}
{% endblock %}
 
{% block content %}
   <div class="container-fluid" align="center">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for book in books %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ book.get_absolute_url }}">
                                <img src="{% if book.image %} {{ book.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ book.get_absolute_url }}">{{ book.book_title }}</a>
                                </h3>
                                <p class="text-center"> {{ book.author }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>
 
 
          </div>
 
        </div>
 
        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <h4>Categories</h4>
            <ol class="list-unstyled">
                <li {% if not category %} class="active"{% endif %}><a href="{% url 'librarian:book_list' %}">All Categories</a></li>
            {% for c in categories %}
 
              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div>
      </div>
 
    </div>
{% endblock %}

librarian/templates/librarian/footer.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" align="center" style="margin-bottom: 0px; background-color: #5AC8FA;">

  <div class="container-fluid navbar-left">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'librarian:book_list' %}" style="color: #ffffff"><h1>LIBRARY CATALOGUE</h1></a>
<div style: align="center", background-color="#ffffff", id="sammix_footer" margin-bottom="20px">

        Copyright © 2018 <a href="#">online library catalog</a> -
        Designed by <a href="#" target="_parent">sam and sharon</a>

</div>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">{{ request.user.username }}<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="">logout</a></li>
          <li class="divider"></li>
          <a href="#" style="color: #ffffff" >Sign in</a>
         <a href="#" style="color: #ffffff">Sign up</a>
        </ul>
      </li>
    </ul>
  </div>
  </div>
</nav>

librarian/templates/librarian/login.html
{% block title %}Login{% endblock %}

    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post"
                <table class="table">
                    <tr>
                        <td><label for="id_username">Username</label></td>
                        <td><input id="id_username" name="username"
                                   type="text" class="form-control"></td>

                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="password"
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login"
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>

librarian/templates/librarian/navbar.html
{% load static %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" align="center" style="margin-bottom: 0px; background-color: #5AC8FA;">

  <div class="container-fluid navbar-left">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'librarian:book_list' %}" style="color: #ffffff"><h1>MY LIBRARY</h1></a>


    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">Welcome   ,{{ request.user.username }}<b class="caret"></b></a>
        <h2 class="dropdown-menu">
          <li><a href="">logout</a></li>
          <li class="divider"></li>
      <li><a href="#" style="color: #ffffff" >Sign in</a></li>
          <li><a href="#" style="color: #ffffff">Sign up</a></h2></li>
        </ul>
      </li>
    </ul>
  </div>
  </div>
</nav>

librarian/templates/librarian/search.html
<form action="/" method="post" type="round">
<input type="text" name="term" size="30" default="enter book title/author">
    <input type="submit" value="Search">
</form>

librarian/templates/login.html
{% extends 'librarian/base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post"
                  action="{% url 'django.contrib.auth.views.login' %}">
                {% csrf_token %}
                {{ form.as_p }}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Username</label></td>
                        <td><input id="id_username" name="username"
                                   type="text" class="form-control"></td>
                                   type="text" class="form-control"></td>
                                   type="text" class="form-control"></td>
                                   type="text" class="form-control"></td>
                                   type="text" class="form-control"></td>
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Password</label></td>
                        <td><input id="id_password" name="password"
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match.
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login"
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}